import groovy.json.JsonBuilder
import groovy.json.JsonOutput

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {
    String greeting ="Duh"

    static void main(String[] args) {
        System.out.println(new App().greeting);

        def lista = [1,2,3]
        println lista

        def mappi = [avain:"arvo", toinen:"muuarvo"]
        println mappi

        int numero = 5
        println numero.class
        def teksti = new String("ABC")
        def toinen = new String("ABC")
        if(teksti==toinen) println "Höhö"

        lista.each {
            println it
        }

        mappi.each { key, value ->
            //println key + " " + value
            println "${key} ${value.size()}"
        }

        def navigointi = new Esimerkki()
        println navigointi

        if(navigointi.npe?.size()) {
            println "jee"
        }

        Esimerkki toinenNavi = [npe:"Tekstiä"]
        println toinenNavi

        Esimerkki kolmasKons = new Esimerkki(npe:"Tekstiä")

        def numeroita = 0..15

        println numeroita

        def kirjaimia = 'a'..'ä'
        println kirjaimia

        def stringi ="Input"
        println stringi ==~ /Ou.*/

        JsonBuilder builder = new JsonBuilder()
        builder.movies {
            movie {
                name "Seitsemän samuraita"
                director "Akira Kurosawa"
                year 1954
                media {
                    type "bluray"
                }
            }
        }

        def json = JsonOutput.prettyPrint(builder.toString())
        println json

















    }
}
